In [1]:
import pandas as pd
import numpy as np


In [10]:
#import necessary packages
from matplotlib import pyplot as plt
from numpy import mean
from numpy import std
from scipy.stats import sem
from scipy import stats
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.model_selection import RepeatedKFold
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score

In [3]:
#Import the data --> this file represents only the train set
data_train = pd.read_csv("Train_set_CC.csv", encoding = "latin-1")
del data_train["Unnamed: 0"]
data_train.head()

FV_D  FV_M     FV_DATE          VISIT_CODE    WP_ID   NAICS  RegCode  \
0    29     6  2019-06-29  2019-06-29 2093649  2093649  812115        3   
1    25     2  2019-02-25  2019-02-25 1095872  1095872  812330        2   
2    19     6  2019-06-19  2019-06-19 2091294  2091294  812190        2   
3     6     5  2019-05-06  2019-05-06 2029237  2029237  238990        4   
4    25    10  2019-10-25  2019-10-25 2125435  2125435  236110        4   

   INDCode  HICCode  HICPerCode  E1524Code  E2554Code  E55pCode  ConCode  \
0       10        1           2          1          1         2        1   
1       10        2           2          1          1         2        4   
2       10        2           2          1          1         2        4   
3        4        5           5          2          2         2        1   
4        4        5           5          2          2         2        3   

   Claims_Code  
0            1  
1            1  
2            1  
3            3  
4            3

In [4]:
data_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19070 entries, 0 to 19069
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   FV_D         19070 non-null  int64 
 1   FV_M         19070 non-null  int64 
 2   FV_DATE      19070 non-null  object
 3   VISIT_CODE   19070 non-null  object
 4   WP_ID        19070 non-null  int64 
 5   NAICS        19070 non-null  int64 
 6   RegCode      19070 non-null  int64 
 7   INDCode      19070 non-null  int64 
 8   HICCode      19070 non-null  int64 
 9   HICPerCode   19070 non-null  int64 
 10  E1524Code    19070 non-null  int64 
 11  E2554Code    19070 non-null  int64 
 12  E55pCode     19070 non-null  int64 
 13  ConCode      19070 non-null  int64 
 14  Claims_Code  19070 non-null  int64 
dtypes: int64(13), object(2)
memory usage: 2.2+ MB


In [5]:
data_train.isnull().sum()

FV_D           0
FV_M           0
FV_DATE        0
VISIT_CODE     0
WP_ID          0
NAICS          0
RegCode        0
INDCode        0
HICCode        0
HICPerCode     0
E1524Code      0
E2554Code      0
E55pCode       0
ConCode        0
Claims_Code    0
dtype: int64

In [6]:
#Import the test data --> this file represents only the test set
data_test = pd.read_csv("Test_set_CC.csv", encoding = "latin-1")
del data_test["Unnamed: 0"]
data_test.head()

FV_D  FV_M     FV_DATE          VISIT_CODE    WP_ID   NAICS  RegCode  \
0    14     2  2019-02-14  2019-02-14 1123343  1123343  212232        5   
1    10     3  2019-03-10  2019-03-10 2006027  2006027  236110        3   
2     6     6  2019-06-06  2019-06-06 2088395  2088395  811199        2   
3    16     5  2019-05-16  2019-05-16 2043065  2043065  236220        2   
4    23    10  2019-10-23  2019-10-23 2123856  2123856  236220        3   

   INDCode  HICCode  HICPerCode  E1524Code  E2554Code  E55pCode  ConCode  \
0        2        1           3          1          2         1        1   
1        4        2           3          2          2         2        1   
2       10        2           2          1          1         2        4   
3        4        6           4          2          2         2        1   
4        4        2           3          2          2         2        4   

   Claims_Code  
0            1  
1            2  
2            1  
3            4  
4            2

In [16]:
#Use the best feature selection method from training

X_tr = data_train.drop(['FV_D', 'FV_M','FV_DATE', 'VISIT_CODE', 'WP_ID', 'NAICS', 'HICPerCode','E1524Code', 'E55pCode','ConCode','Claims_Code'], axis = 1)
y_tr = data_train['Claims_Code']

X_ts = data_test.drop(['FV_D', 'FV_M','FV_DATE', 'VISIT_CODE', 'WP_ID', 'NAICS', 'HICPerCode','E1524Code', 'E55pCode','ConCode','Claims_Code'], axis = 1)
y_ts = data_test['Claims_Code']

print(list(X_tr.columns.values))
print(list(X_ts.columns.values))
print(X_tr.shape, y_tr.shape, X_ts.shape, y_ts.shape, )                       


['RegCode', 'INDCode', 'HICCode', 'E2554Code']
['RegCode', 'INDCode', 'HICCode', 'E2554Code']
(19070, 4) (19070,) (8173, 4) (8173,)


In [6]:
#using the train set define the features (X) and target (y) --> using Claims_Code as dependent variable
#features identified during Feature Selection via RFE 1 -->  RegCode, INDCode, HICCode, E2554Code

X = data.drop(['FV_D', 'FV_M','FV_DATE', 'VISIT_CODE', 'WP_ID', 'NAICS', 'HICPerCode','E1524Code', 'E55pCode','ConCode','Claims_Code'], axis=1)
y = data['Claims_Code']

print(list(X.columns.values))  #Features used in the model
print(X.shape, y.shape)
print(y.value_counts())

['RegCode', 'INDCode', 'HICCode', 'E2554Code']


In [8]:
#X_tr, X_ts, y_tr, y_ts = train_test_split(X, y,  train_size = .70, random_state = 23)

RANDOM FOREST MODEL

In [18]:
#Running model with timing
#Optimal max features = 4, min samples in leaf = 1, number of estimators = 50

import time
start = time.time()

#configure the function for the Random Forest Model

RF_model = RandomForestClassifier(n_estimators = 50, max_features = 4)  
RF_model.fit(X_tr, y_tr)
print(RF_model.fit(X_tr, y_tr))

y_predicted = RF_model.predict(X_ts)

#Create confusion matrix

from sklearn.metrics import confusion_matrix
con_matx = confusion_matrix(y_ts, y_predicted)
print(con_matx)

#Accuracy score
print(accuracy_score(y_ts, y_predicted))

#Create the report for the classification model
from sklearn.metrics import classification_report
print(classification_report(y_ts, y_predicted))

end = time.time()

print('Amount of time to run KNN model = %.8f' %(end-start))


RandomForestClassifier(max_features=4, n_estimators=50)
[[1752    0    0    0    0]
 [   0 1842    0    0    0]
 [   0    0 1284    0    0]
 [   0    0    0 1868    0]
 [   0    0    0    0 1427]]
1.0
              precision    recall  f1-score   support

           1       1.00      1.00      1.00      1752
           2       1.00      1.00      1.00      1842
           3       1.00      1.00      1.00      1284
           4       1.00      1.00      1.00      1868
           5       1.00      1.00      1.00      1427

    accuracy                           1.00      8173
   macro avg       1.00      1.00      1.00      8173
weighted avg       1.00      1.00      1.00      8173

Amount of time to run KNN model = 1.07692432
