In [1]:
import pandas as pd
import numpy as np


In [2]:
#import necessary packages
from matplotlib import pyplot as plt
from numpy import mean
from numpy import std
from math import sqrt
from scipy.stats import sem
from scipy import stats
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier  
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.model_selection import RepeatedKFold
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
from sklearn import metrics

In [3]:
#Import the data --> this file represents only the train set
data_train = pd.read_csv("Train_set_CC.csv", encoding = "latin-1")
del data_train["Unnamed: 0"]
data_train.head()

FV_D  FV_M     FV_DATE          VISIT_CODE    WP_ID   NAICS  RegCode  \
0    29     6  2019-06-29  2019-06-29 2093649  2093649  812115        3   
1    25     2  2019-02-25  2019-02-25 1095872  1095872  812330        2   
2    19     6  2019-06-19  2019-06-19 2091294  2091294  812190        2   
3     6     5  2019-05-06  2019-05-06 2029237  2029237  238990        4   
4    25    10  2019-10-25  2019-10-25 2125435  2125435  236110        4   

   INDCode  HICCode  HICPerCode  E1524Code  E2554Code  E55pCode  ConCode  \
0       10        1           2          1          1         2        1   
1       10        2           2          1          1         2        4   
2       10        2           2          1          1         2        4   
3        4        5           5          2          2         2        1   
4        4        5           5          2          2         2        3   

   Claims_Code  
0            1  
1            1  
2            1  
3            3  
4            3

In [4]:
data_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19070 entries, 0 to 19069
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   FV_D         19070 non-null  int64 
 1   FV_M         19070 non-null  int64 
 2   FV_DATE      19070 non-null  object
 3   VISIT_CODE   19070 non-null  object
 4   WP_ID        19070 non-null  int64 
 5   NAICS        19070 non-null  int64 
 6   RegCode      19070 non-null  int64 
 7   INDCode      19070 non-null  int64 
 8   HICCode      19070 non-null  int64 
 9   HICPerCode   19070 non-null  int64 
 10  E1524Code    19070 non-null  int64 
 11  E2554Code    19070 non-null  int64 
 12  E55pCode     19070 non-null  int64 
 13  ConCode      19070 non-null  int64 
 14  Claims_Code  19070 non-null  int64 
dtypes: int64(13), object(2)
memory usage: 2.2+ MB


In [5]:
data_train.isnull().sum()

FV_D           0
FV_M           0
FV_DATE        0
VISIT_CODE     0
WP_ID          0
NAICS          0
RegCode        0
INDCode        0
HICCode        0
HICPerCode     0
E1524Code      0
E2554Code      0
E55pCode       0
ConCode        0
Claims_Code    0
dtype: int64

In [6]:
#Import the test data --> this file represents only the test set
data_test = pd.read_csv("Test_set_CC.csv", encoding = "latin-1")
del data_test["Unnamed: 0"]
data_test.head()

FV_D  FV_M     FV_DATE          VISIT_CODE    WP_ID   NAICS  RegCode  \
0    14     2  2019-02-14  2019-02-14 1123343  1123343  212232        5   
1    10     3  2019-03-10  2019-03-10 2006027  2006027  236110        3   
2     6     6  2019-06-06  2019-06-06 2088395  2088395  811199        2   
3    16     5  2019-05-16  2019-05-16 2043065  2043065  236220        2   
4    23    10  2019-10-23  2019-10-23 2123856  2123856  236220        3   

   INDCode  HICCode  HICPerCode  E1524Code  E2554Code  E55pCode  ConCode  \
0        2        1           3          1          2         1        1   
1        4        2           3          2          2         2        1   
2       10        2           2          1          1         2        4   
3        4        6           4          2          2         2        1   
4        4        2           3          2          2         2        4   

   Claims_Code  
0            1  
1            2  
2            1  
3            4  
4            2

In [7]:
#Use the best feature selection method from training

X_tr = data_train.drop(['FV_D', 'FV_M', 'FV_DATE', 'VISIT_CODE', 'RegCode', 'E2554Code', 'E1524Code', 'E55pCode','ConCode', 'Claims_Code'], axis = 1)
y_tr = data_train['Claims_Code']

X_ts = data_test.drop(['FV_D', 'FV_M', 'FV_DATE', 'VISIT_CODE', 'RegCode', 'E2554Code', 'E1524Code', 'E55pCode','ConCode', 'Claims_Code'], axis = 1)
y_ts = data_test['Claims_Code']

print(list(X_tr.columns.values))
print(list(X_ts.columns.values))
print(X_tr.shape, y_tr.shape, X_ts.shape, y_ts.shape, )                       


['WP_ID', 'NAICS', 'INDCode', 'HICCode', 'HICPerCode']
['WP_ID', 'NAICS', 'INDCode', 'HICCode', 'HICPerCode']
(19070, 5) (19070,) (8173, 5) (8173,)


In [8]:
#X_tr, X_ts, y_tr, y_ts = train_test_split(X, y,  train_size = .70, random_state = 23)

In [9]:
#Running model with timing
#Optimal k = 3

import time
start = time.time()
#configure the KNN function for KNN classification model

KNN_model = KNeighborsClassifier(n_neighbors=3) 
KNN_model.fit(X_tr, y_tr) 
print(KNN_model.fit(X_tr, y_tr))

y_predicted = KNN_model.predict(X_ts)

#create the confusion matrix
from sklearn.metrics import confusion_matrix
con_matx = confusion_matrix(y_ts, y_predicted)
print(con_matx)

#accuracy score
from sklearn.metrics import accuracy_score
print('Accuracy is %.2f' %(accuracy_score(y_ts, y_predicted)))


#create the report for the classification model
from sklearn.metrics import classification_report
print(classification_report(y_ts, y_predicted))

end = time.time()

print('Amount of time to run KNN model = %.8f' %(end-start))

KNeighborsClassifier(n_neighbors=3)
[[1424  147   57  105   19]
 [ 262  891  186  384  119]
 [ 166  297  459  290   72]
 [ 180  440  213 1009   26]
 [  47   62   48   26 1244]]
Accuracy is 0.62
              precision    recall  f1-score   support

           1       0.68      0.81      0.74      1752
           2       0.49      0.48      0.48      1842
           3       0.48      0.36      0.41      1284
           4       0.56      0.54      0.55      1868
           5       0.84      0.87      0.86      1427

    accuracy                           0.62      8173
   macro avg       0.61      0.61      0.61      8173
weighted avg       0.60      0.62      0.61      8173

Amount of time to run KNN model = 0.24664664
